<?php
if ($_SESSION['userType'] == "Admin") {
    include('views/adminHeader.php');
} else {
    include('views/regularHeader.php');
}
?>

<?php

?>
<body>

    <div class="container text-center">
        <div class='headings'><h1>Welcome To The Employee Management System</h1></div>
        
    </div>

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Platea dictumst quisque sagittis purus sit amet. Consectetur adipiscing elit pellentesque habitant morbi. Vel eros donec ac odio tempor orci dapibus ultrices. Diam ut venenatis tellus in. Adipiscing diam donec adipiscing tristique risus. Ut porttitor leo a diam sollicitudin tempor id. Sit amet nisl purus in. Eget lorem dolor sed viverra. Est ante in nibh mauris cursus. Consequat mauris nunc congue nisi vitae suscipit tellus. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Faucibus a pellentesque sit amet porttitor eget dolor. Proin sed libero enim sed faucibus.

        Tempus egestas sed sed risus pretium. Ut ornare lectus sit amet. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Augue neque gravida in fermentum et sollicitudin ac orci phasellus. In arcu cursus euismod quis. Neque aliquam vestibulum morbi blandit cursus risus at. Sit amet est placerat in egestas erat imperdiet. Et magnis dis parturient montes nascetur ridiculus. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Eu scelerisque felis imperdiet proin. Ultrices sagittis orci a scelerisque purus semper eget duis. Pellentesque habitant morbi tristique senectus et netus et. Dolor magna eget est lorem ipsum dolor sit amet. Ullamcorper a lacus vestibulum sed arcu non. Eu non diam phasellus vestibulum lorem sed. Diam quam nulla porttitor massa id. Augue interdum velit euismod in. Proin nibh nisl condimentum id venenatis a condimentum vitae.

        A condimentum vitae sapien pellentesque habitant morbi tristique senectus. Maecenas sed enim ut sem viverra aliquet eget sit amet. Ut lectus arcu bibendum at varius. Hendrerit dolor magna eget est lorem. Morbi tincidunt augue interdum velit euismod in pellentesque massa. Quam viverra orci sagittis eu volutpat. Congue quisque egestas diam in arcu cursus euismod quis viverra. Malesuada fames ac turpis egestas sed tempus. Sit amet venenatis urna cursus. A condimentum vitae sapien pellentesque habitant. Scelerisque purus semper eget duis at tellus at urna. Consequat id porta nibh venenatis cras sed felis. Varius duis at consectetur lorem donec massa. Aenean euismod elementum nisi quis eleifend quam. Ultricies leo integer malesuada nunc vel risus commodo viverra. At consectetur lorem donec massa sapien faucibus et. Id nibh tortor id aliquet lectus proin nibh. Morbi tincidunt augue interdum velit euismod in pellentesque massa.

        Faucibus purus in massa tempor nec feugiat nisl pretium fusce. Sem viverra aliquet eget sit amet. Id volutpat lacus laoreet non curabitur gravida arcu ac tortor. Arcu risus quis varius quam quisque id diam vel. Sed pulvinar proin gravida hendrerit lectus. Orci porta non pulvinar neque laoreet suspendisse interdum. Fusce ut placerat orci nulla pellentesque dignissim. Justo donec enim diam vulputate ut pharetra sit. Tellus molestie nunc non blandit massa enim nec dui. Sed arcu non odio euismod lacinia at quis. Sed risus ultricies tristique nulla aliquet enim tortor at auctor. Sapien pellentesque habitant morbi tristique senectus. Feugiat in fermentum posuere urna nec tincidunt praesent. Leo vel orci porta non pulvinar neque laoreet.

        Tortor pretium viverra suspendisse potenti nullam. Vel fringilla est ullamcorper eget nulla facilisi. Commodo quis imperdiet massa tincidunt. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum posuere. Faucibus nisl tincidunt eget nullam non nisi. Vel quam elementum pulvinar etiam non quam lacus. Enim sed faucibus turpis in eu mi bibendum neque egestas. Lectus mauris ultrices eros in cursus turpis. Vulputate mi sit amet mauris. In nisl nisi scelerisque eu ultrices vitae auctor. Etiam sit amet nisl purus in mollis nunc. Ipsum faucibus vitae aliquet nec ullamcorper. Auctor urna nunc id cursus metus aliquam eleifend mi. Elementum nibh tellus molestie nunc non blandit massa enim nec. Mattis aliquam faucibus purus in massa tempor nec feugiat.

        Scelerisque fermentum dui faucibus in. Quam viverra orci sagittis eu volutpat odio facilisis. Mi bibendum neque egestas congue quisque. Ullamcorper eget nulla facilisi etiam. Nec sagittis aliquam malesuada bibendum arcu vitae elementum. Morbi non arcu risus quis varius. Risus nec feugiat in fermentum posuere urna nec tincidunt praesent. Pharetra diam sit amet nisl. Amet nisl suscipit adipiscing bibendum est ultricies. Vulputate dignissim suspendisse in est ante in nibh mauris cursus. Nec ullamcorper sit amet risus nullam eget felis eget. Elit at imperdiet dui accumsan sit amet nulla facilisi. Sed euismod nisi porta lorem mollis. Volutpat diam ut venenatis tellus in metus vulputate. Varius vel pharetra vel turpis nunc eget lorem dolor sed. Viverra mauris in aliquam sem fringilla ut morbi tincidunt. Accumsan lacus vel facilisis volutpat. Ut sem nulla pharetra diam sit amet. Fusce id velit ut tortor pretium viverra suspendisse potenti.

        Neque vitae tempus quam pellentesque nec nam aliquam sem et. Ac odio tempor orci dapibus ultrices in iaculis nunc sed. Ut ornare lectus sit amet est placerat in egestas erat. Nisi vitae suscipit tellus mauris a diam maecenas sed. Sapien pellentesque habitant morbi tristique senectus et netus et. Fermentum leo vel orci porta non pulvinar neque laoreet. Ac turpis egestas maecenas pharetra convallis. Vel quam elementum pulvinar etiam non quam. Sed turpis tincidunt id aliquet risus feugiat in. Ornare quam viverra orci sagittis eu. Aliquam ut porttitor leo a diam sollicitudin tempor id eu.

        Nec ultrices dui sapien eget mi proin sed. Id venenatis a condimentum vitae sapien pellentesque. Amet aliquam id diam maecenas ultricies mi eget mauris. Morbi tempus iaculis urna id volutpat lacus laoreet non curabitur. Vitae nunc sed velit dignissim sodales ut eu. Nibh mauris cursus mattis molestie a iaculis at erat pellentesque. Adipiscing diam donec adipiscing tristique risus nec. Non odio euismod lacinia at quis risus sed vulputate odio. Tortor condimentum lacinia quis vel eros donec ac. Tristique senectus et netus et malesuada. Dui nunc mattis enim ut tellus elementum. Mattis nunc sed blandit libero volutpat. Gravida in fermentum et sollicitudin ac orci phasellus egestas. In pellentesque massa placerat duis. Nisl vel pretium lectus quam id leo. Eget mauris pharetra et ultrices neque ornare aenean.

        Commodo nulla facilisi nullam vehicula ipsum a arcu cursus. Viverra nam libero justo laoreet sit amet. Adipiscing commodo elit at imperdiet. Ullamcorper malesuada proin libero nunc consequat interdum varius sit amet. Quisque non tellus orci ac. Euismod elementum nisi quis eleifend quam adipiscing vitae proin. Lorem mollis aliquam ut porttitor leo. Lacus sed turpis tincidunt id aliquet risus feugiat in. Faucibus et molestie ac feugiat sed. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. At risus viverra adipiscing at in tellus integer feugiat scelerisque. In iaculis nunc sed augue lacus. Blandit aliquam etiam erat velit scelerisque in dictum non consectetur. Ultrices sagittis orci a scelerisque purus semper. Nulla aliquet enim tortor at auctor urna nunc.

        Pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Mi in nulla posuere sollicitudin aliquam ultrices sagittis. Pretium nibh ipsum consequat nisl vel pretium. Facilisis magna etiam tempor orci eu. Maecenas ultricies mi eget mauris. Aenean sed adipiscing diam donec adipiscing tristique risus. Amet massa vitae tortor condimentum lacinia quis vel eros donec. Semper quis lectus nulla at volutpat diam ut venenatis tellus. Facilisis leo vel fringilla est ullamcorper eget. Auctor elit sed vulputate mi sit amet. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend.

        Ipsum a arcu cursus vitae congue mauris. Auctor urna nunc id cursus. Ac tortor dignissim convallis aenean et tortor at risus viverra. Fermentum dui faucibus in ornare quam viverra orci. Ut tellus elementum sagittis vitae et. Dui ut ornare lectus sit amet est placerat. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh. Tellus at urna condimentum mattis pellentesque id nibh tortor id. Auctor augue mauris augue neque gravida in. Praesent tristique magna sit amet purus gravida quis. Pellentesque massa placerat duis ultricies lacus sed turpis tincidunt id.

        Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Ut eu sem integer vitae justo eget magna fermentum iaculis. Nulla pharetra diam sit amet. Neque laoreet suspendisse interdum consectetur libero id. Metus aliquam eleifend mi in. Nunc sed blandit libero volutpat sed cras ornare. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Quisque egestas diam in arcu cursus euismod quis viverra. Mi quis hendrerit dolor magna eget est lorem. Odio eu feugiat pretium nibh. Vulputate eu scelerisque felis imperdiet proin. Faucibus ornare suspendisse sed nisi lacus sed viverra. Auctor urna nunc id cursus metus.

        Mattis molestie a iaculis at erat pellentesque. Sed nisi lacus sed viverra. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Orci sagittis eu volutpat odio facilisis mauris sit amet. Hac habitasse platea dictumst quisque. Iaculis nunc sed augue lacus viverra vitae congue. Sit amet porttitor eget dolor morbi non arcu risus. Mi tempus imperdiet nulla malesuada pellentesque. Nibh sed pulvinar proin gravida hendrerit lectus a. Purus sit amet volutpat consequat mauris nunc congue nisi vitae. Nec ullamcorper sit amet risus nullam. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Nisl purus in mollis nunc sed. Sit amet mauris commodo quis imperdiet massa tincidunt. In eu mi bibendum neque egestas. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Quam pellentesque nec nam aliquam sem. Velit aliquet sagittis id consectetur purus ut. Libero nunc consequat interdum varius sit amet mattis vulputate. Hendrerit dolor magna eget est lorem ipsum dolor.

        Morbi enim nunc faucibus a pellentesque. Senectus et netus et malesuada fames ac turpis egestas integer. Adipiscing vitae proin sagittis nisl rhoncus. Tortor at auctor urna nunc id cursus. Aenean sed adipiscing diam donec adipiscing. Rhoncus mattis rhoncus urna neque viverra justo nec. Feugiat scelerisque varius morbi enim nunc faucibus a. Euismod elementum nisi quis eleifend quam adipiscing. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Pulvinar pellentesque habitant morbi tristique senectus et. Vel facilisis volutpat est velit egestas dui. Est ante in nibh mauris cursus mattis molestie a.

        Sit amet facilisis magna etiam tempor orci eu. Aliquam faucibus purus in massa tempor nec feugiat nisl pretium. Ultrices sagittis orci a scelerisque purus semper eget duis. Suscipit tellus mauris a diam maecenas sed enim ut sem. Enim eu turpis egestas pretium aenean pharetra magna ac placerat. Lobortis elementum nibh tellus molestie nunc non. Amet nulla facilisi morbi tempus iaculis urna id. Dapibus ultrices in iaculis nunc sed augue lacus. In egestas erat imperdiet sed. Nunc mattis enim ut tellus elementum sagittis vitae. Commodo ullamcorper a lacus vestibulum. Velit dignissim sodales ut eu sem integer vitae. Vel facilisis volutpat est velit egestas dui.
    </p>
</body>

